// Mock data for TaxPlan Advisor - RLS-ready with consultantId and clientId

export const mockClients = [
  {
    id: 'client_001',
    consultantId: 'consultant_001',
    name: 'Rajesh Kumar Industries',
    email: 'rajesh@rkind.com',
    phone: '+91 98765 43210',
    pan: 'ABCPK1234A',
    gstin: '27ABCPK1234A1Z5',
    status: 'active',
    avatarUrl: '',
    createdAt: '2023-06-15',
    lastActivity: '2024-01-08',
  },
  {
    id: 'client_002',
    consultantId: 'consultant_001',
    name: 'Sharma Textiles Pvt Ltd',
    email: 'accounts@sharmatextiles.in',
    phone: '+91 87654 32109',
    pan: 'AADCS5678B',
    gstin: '27AADCS5678B1Z4',
    status: 'active',
    avatarUrl: '',
    createdAt: '2023-08-22',
    lastActivity: '2024-01-10',
  },
  {
    id: 'client_003',
    consultantId: 'consultant_001',
    name: 'Patel Electronics',
    email: 'finance@patelelectronics.com',
    phone: '+91 76543 21098',
    pan: 'AABCP9012C',
    gstin: '27AABCP9012C1Z3',
    status: 'pending',
    avatarUrl: '',
    createdAt: '2024-01-02',
    lastActivity: '2024-01-09',
  },
  {
    id: 'client_004',
    consultantId: 'consultant_001',
    name: 'Mehta Constructions',
    email: 'cfo@mehtaconstructions.in',
    phone: '+91 65432 10987',
    pan: 'AABCM3456D',
    gstin: '27AABCM3456D1Z2',
    status: 'inactive',
    avatarUrl: '',
    createdAt: '2022-03-10',
    lastActivity: '2023-12-15',
  },
  {
    id: 'client_005',
    consultantId: 'consultant_001',
    name: 'Singh Pharmaceuticals',
    email: 'tax@singhpharma.com',
    phone: '+91 54321 09876',
    pan: 'AABCS7890E',
    gstin: '27AABCS7890E1Z1',
    status: 'active',
    avatarUrl: '',
    createdAt: '2023-04-18',
    lastActivity: '2024-01-10',
  },
];

export const mockDocuments = [
  {
    id: 1,
    consultant: 1,
    consultant_name: 'Consultant One',
    client: 1,
    client_name: 'Rajesh Kumar Industries',
    title: 'Bank Statement - HDFC Jan 2024',
    description: 'Monthly bank statement for January',
    status: 'VERIFIED',
    file: '/media/vault/client_1/st_001.pdf',
    created_at: '2024-01-08T10:00:00Z',
    uploaded_at: '2024-01-08T10:30:00Z',
  },
  {
    id: 2,
    consultant: 1,
    consultant_name: 'Consultant One',
    client: 1,
    client_name: 'Rajesh Kumar Industries',
    title: 'PAN Card - Rajesh Kumar',
    description: 'ID proof for verification',
    status: 'VERIFIED',
    file: '/media/vault/client_1/pan_rajesh.jpg',
    created_at: '2024-01-05T14:00:00Z',
    uploaded_at: '2024-01-05T14:20:00Z',
  },
  {
    id: 3,
    consultant: 1,
    consultant_name: 'Consultant One',
    client: 2,
    client_name: 'Sharma Textiles Pvt Ltd',
    title: 'GST Return - Dec 2023',
    description: 'GSTR-1 filing copy',
    status: 'UPLOADED',
    file: '/media/vault/client_2/gst_dec.pdf',
    created_at: '2024-01-10T08:00:00Z',
    uploaded_at: '2024-01-10T08:45:00Z',
  },
  {
    id: 4,
    consultant: 1,
    consultant_name: 'Consultant One',
    client: 3,
    client_name: 'Patel Electronics',
    title: 'ITR-3 FY 2022-23',
    description: 'Income Tax Return draft',
    status: 'PENDING',
    file: null,
    created_at: '2024-01-09T16:00:00Z',
    uploaded_at: null,
  },
];

export const mockSharedReports = [
  {
    id: 1,
    consultant: 1,
    consultant_name: 'Consultant One',
    client: 1,
    client_name: 'Rajesh Kumar Industries',
    title: 'Annual CMA Report 2023',
    description: 'Consolidated CMA for loan application',
    file: '/media/reports/client_1/cma_2023.pdf',
    report_type: 'CMA',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    consultant: 1,
    consultant_name: 'Consultant One',
    client: 2,
    client_name: 'Sharma Textiles Pvt Ltd',
    title: 'GST Reconciliation Q3',
    description: 'GSTR 2B vs Books recon',
    file: '/media/reports/client_2/gst_recon_q3.xlsx',
    report_type: 'GST',
    created_at: '2024-01-12T11:30:00Z',
  },
];

export const mockActivities = [
  {
    id: 'activity_001',
    clientId: 'client_001',
    type: 'whatsapp',
    title: 'Message sent',
    description: 'Reminder for bank statement submission',
    timestamp: '2024-01-10T09:30:00Z',
  },
  {
    id: 'activity_002',
    clientId: 'client_001',
    type: 'document',
    title: 'Document uploaded',
    description: 'Bank Statement - HDFC Jan 2024',
    timestamp: '2024-01-08T10:30:00Z',
  },
  {
    id: 'activity_003',
    clientId: 'client_001',
    type: 'call',
    title: 'Call completed',
    description: 'Discussed GST filing timeline - 8 min',
    timestamp: '2024-01-07T14:15:00Z',
  },
  {
    id: 'activity_004',
    clientId: 'client_002',
    type: 'system',
    title: 'Status changed',
    description: 'GST Return moved to Submitted',
    timestamp: '2024-01-10T08:45:00Z',
  },
  {
    id: 'activity_005',
    clientId: 'client_002',
    type: 'whatsapp',
    title: 'Message received',
    description: 'Client confirmed invoice details',
    timestamp: '2024-01-09T11:20:00Z',
  },
];

export const mockChatMessages = [
  {
    id: 'msg_001',
    clientId: 'client_001',
    direction: 'sent',
    content: 'Good morning! Please share your bank statement for January 2024.',
    timestamp: '2024-01-08T09:00:00Z',
    status: 'read',
    type: 'text',
  },
  {
    id: 'msg_002',
    clientId: 'client_001',
    direction: 'received',
    content: 'Good morning! I will send it by today evening.',
    timestamp: '2024-01-08T09:15:00Z',
    status: 'read',
    type: 'text',
  },
  {
    id: 'msg_003',
    clientId: 'client_001',
    direction: 'received',
    content: 'Here is the bank statement as requested.',
    timestamp: '2024-01-08T18:30:00Z',
    status: 'read',
    type: 'document',
  },
  {
    id: 'msg_004',
    clientId: 'client_001',
    direction: 'sent',
    content: 'Thank you! I have received the document and will process it shortly.',
    timestamp: '2024-01-08T18:45:00Z',
    status: 'delivered',
    type: 'text',
  },
  {
    id: 'msg_005',
    clientId: 'client_001',
    direction: 'sent',
    content: 'Reminder: Your GST filing deadline is approaching on January 20th.',
    timestamp: '2024-01-10T09:30:00Z',
    status: 'sent',
    type: 'template',
  },
];

export const mockGSTRecords = [
  {
    id: 'gst_001',
    consultantId: 'consultant_001',
    clientId: 'client_002',
    gstin: '27AADCS5678B1Z4',
    supplierName: 'ABC Trading Co.',
    invoiceNo: 'INV-2024-001',
    invoiceDate: '2024-01-05',
    booksValue: 125000,
    gstr2bValue: 125000,
    difference: 0,
    status: 'matched',
  },
  {
    id: 'gst_002',
    consultantId: 'consultant_001',
    clientId: 'client_002',
    gstin: '27AADCS5678B1Z4',
    supplierName: 'XYZ Suppliers Ltd.',
    invoiceNo: 'INV-2024-002',
    invoiceDate: '2024-01-08',
    booksValue: 85000,
    gstr2bValue: 82500,
    difference: 2500,
    status: 'unmatched',
  },
  {
    id: 'gst_003',
    consultantId: 'consultant_001',
    clientId: 'client_002',
    gstin: '27AADCS5678B1Z4',
    supplierName: 'PQR Industries',
    invoiceNo: 'INV-2024-003',
    invoiceDate: '2024-01-10',
    booksValue: 0,
    gstr2bValue: 45000,
    difference: -45000,
    status: 'missing_in_books',
  },
  {
    id: 'gst_004',
    consultantId: 'consultant_001',
    clientId: 'client_002',
    gstin: '27AADCS5678B1Z4',
    supplierName: 'LMN Enterprises',
    invoiceNo: 'INV-2024-004',
    invoiceDate: '2024-01-12',
    booksValue: 67500,
    gstr2bValue: 0,
    difference: 67500,
    status: 'missing_in_gstr2b',
  },
  {
    id: 'gst_005',
    consultantId: 'consultant_001',
    clientId: 'client_002',
    gstin: '27AADCS5678B1Z4',
    supplierName: 'DEF Corporation',
    invoiceNo: 'INV-2024-005',
    invoiceDate: '2024-01-15',
    booksValue: 198000,
    gstr2bValue: 198000,
    difference: 0,
    status: 'matched',
  },
];

export const mockConsentRecords = [
  {
    id: 'consent_001',
    consultantId: 'consultant_001',
    clientId: 'client_001',
    purpose: 'Tax Filing Services',
    consentDate: '2023-06-15',
    status: 'active',
    expiryDate: '2024-06-15',
  },
  {
    id: 'consent_002',
    consultantId: 'consultant_001',
    clientId: 'client_001',
    purpose: 'WhatsApp Communication',
    consentDate: '2023-06-15',
    status: 'active',
    expiryDate: '2024-06-15',
  },
  {
    id: 'consent_003',
    consultantId: 'consultant_001',
    clientId: 'client_002',
    purpose: 'Tax Filing Services',
    consentDate: '2023-08-22',
    status: 'active',
    expiryDate: '2024-08-22',
  },
  {
    id: 'consent_004',
    consultantId: 'consultant_001',
    clientId: 'client_004',
    purpose: 'Tax Filing Services',
    consentDate: '2022-03-10',
    status: 'expired',
    expiryDate: '2023-03-10',
  },
];

export const messageTemplates = [
  {
    id: 'template_001',
    category: 'Reminders',
    name: 'Document Reminder',
    content: 'Dear {{client_name}}, this is a gentle reminder to submit your {{document_type}} at the earliest.',
  },
  {
    id: 'template_002',
    category: 'Reminders',
    name: 'GST Filing Deadline',
    content: 'Reminder: Your GST filing deadline is approaching on {{deadline_date}}. Please ensure all documents are ready.',
  },
  {
    id: 'template_003',
    category: 'Updates',
    name: 'Document Processed',
    content: 'Your {{document_type}} has been processed successfully. Please review at your convenience.',
  },
  {
    id: 'template_004',
    category: 'Updates',
    name: 'Payment Received',
    content: 'Thank you! We have received your payment of ₹{{amount}}. Invoice will be shared shortly.',
  },
  {
    id: 'template_005',
    category: 'Greetings',
    name: 'Welcome Message',
    content: 'Welcome to TaxPlan Advisor! We are excited to assist you with your tax compliance needs.',
  },
];
